spring:
  application:
    name: kafka-back-pressure

  datasource:
    url: jdbc:mysql://localhost:3307/orderdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:

      # ===== Pool Identity =====
      pool-name: orderServiceHikariPool

      # ===== Pool Size =====
      maximum-pool-size: 15
      minimum-idle: 5

      # ===== Connection Timeout =====
      connection-timeout: 30000

      # ===== Idle Timeout =====
      idle-timeout: 600000

      # ===== Max Lifetime =====
      max-lifetime: 1800000

      # ===== Validation =====
      validation-timeout: 5000

      # ===== Leak Detection =====
      leak-detection-threshold: 60000

      # ===== Performance =====
      auto-commit: false

      # ===== MySQL Optimization =====
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  jpa:
    hibernate:
      ddl-auto: update

  threads:
    virtual:
      enabled: true

  kafka:

    bootstrap-servers: localhost:9092

    producer:

      acks: all
      retries: 10

      key-serializer: org.apache.kafka.common.serialization.StringSerializer

      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:

        enable.idempotence: true

        linger.ms: 20

    consumer:

      group-id: order-group

      auto-offset-reset: earliest

      enable-auto-commit: false

      max-poll-records: 50

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:

        spring.json.trusted.packages: "*"

        spring.json.value.default.type: com.kafka_back_pressure.dto.OrderEvent

        max.poll.interval.ms: 300000

        session.timeout.ms: 30000

    listener:

      ack-mode: manual

      concurrency: 4

management:
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true